informações sobre as amostras originais:

index 0 a 100 - SAN - 101

index 101 a 283 - CMH - 183

index 284 a 399 - CMD - 116


In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)

In [3]:
df_norm_data = pd.read_csv("../Database/df_database_dados_normalizados_minmax.csv")
df_norm_data.head()

idade  genero    volume     massa      edl1  edl2      edl3  edl4  \
0  0.317647     1.0  0.088660  0.163230  0.004051   0.0  0.145233   0.0   
1  0.341176     1.0  0.129897  0.190722  0.243038   0.0  0.705065   0.0   
2  0.294118     1.0  0.125773  0.243986  0.361519   0.0  0.439921   0.0   
3  0.588235     1.0  0.154639  0.158076  0.000000   0.0  0.121648   0.0   
4  0.635294     1.0  0.076289  0.099656  0.040000   0.0  0.524081   0.0   

       edl5  edl6      edl7  edl8    hough1  hough2    hough3  hough4  \
0  0.204617   0.0  0.541572   0.0  0.003559     0.0  0.126543     0.0   
1  0.000000   0.0  0.000000   0.0  0.227758     0.0  0.695988     0.0   
2  0.024257   0.0  0.144177   0.0  0.387900     0.0  0.484568     0.0   
3  0.031690   0.0  0.407845   0.0  0.000000     0.0  0.097222     0.0   
4  0.000000   0.0  0.064365   0.0  0.032028     0.0  0.495370     0.0   

     hough5  hough6    hough7  hough8   spharm1   spharm2   spharm3   spharm4  \
0  0.187845     0.0  0.641855     0.0  0.674581  0.472682  0.960090  0.615620   
1  0.000000     0.0  0.000000     0.0  0.730882  0.472890  0.960034  0.614617   
2  0.030387     0.0  0.167206     0.0  0.732323  1.000000  0.990207  0.620600   
3  0.024862     0.0  0.436893     0.0  0.731000  0.472816  0.960065  0.615284   
4  0.000000     0.0  0.061489     0.0  0.725301  0.472820  0.960034  0.615304   

    spharm5   spharm6   spharm7   spharm8  target  
0  0.512404  0.320546  0.225202  0.238832       0  
1  0.511467  0.323260  0.224983  0.239064       0  
2  0.551338  0.308642  0.227152  0.237536       0  
3  0.550603  0.323264  0.225098  0.239055       0  
4  0.509081  0.323261  0.224991  0.239020       0

In [4]:
features_indexes = df_norm_data.columns[0:-1]
print(features_indexes)

Index(['idade', 'genero', 'volume', 'massa', 'edl1', 'edl2', 'edl3', 'edl4',
       'edl5', 'edl6', 'edl7', 'edl8', 'hough1', 'hough2', 'hough3', 'hough4',
       'hough5', 'hough6', 'hough7', 'hough8', 'spharm1', 'spharm2', 'spharm3',
       'spharm4', 'spharm5', 'spharm6', 'spharm7', 'spharm8'],
      dtype='object')


In [5]:
df_norm_data_san = df_norm_data[df_norm_data['target']==0]
df_norm_data_san

idade  genero    volume     massa      edl1      edl2      edl3  \
0    0.317647     1.0  0.088660  0.163230  0.004051  0.000000  0.145233   
1    0.341176     1.0  0.129897  0.190722  0.243038  0.000000  0.705065   
2    0.294118     1.0  0.125773  0.243986  0.361519  0.000000  0.439921   
3    0.588235     1.0  0.154639  0.158076  0.000000  0.000000  0.121648   
4    0.635294     1.0  0.076289  0.099656  0.040000  0.000000  0.524081   
5    0.388235     0.0  0.080412  0.151203  0.058228  0.000000  0.116187   
6    0.647059     1.0  0.253608  0.178694  0.018228  0.000000  0.279295   
7    0.423529     1.0  0.164948  0.211340  0.092152  0.000000  0.142751   
8    0.341176     1.0  0.096907  0.161512  0.368101  0.000000  0.154667   
9    0.588235     1.0  0.078351  0.113402  0.000000  0.000000  0.009682   
10   0.388235     1.0  0.152577  0.171821  0.145823  0.000000  0.210030   
11   0.376471     1.0  0.164948  0.211340  0.215696  0.000000  0.436197   
12   0.341176     1.0  0.179381  0.231959  0.193418  0.000000  0.251986   
13   0.388235     1.0  0.259794  0.250859  0.000000  0.000000  0.216981   
14   0.764706     1.0  0.088660  0.168385  0.044557  0.000000  0.299652   
15   0.411765     1.0  0.107216  0.159794  0.108354  0.000000  0.119166   
16   0.258824     1.0  0.177320  0.269759  0.022785  0.000000  0.579940   
17   0.447059     0.0  0.107216  0.137457  0.227342  0.000000  0.292453   
18   0.670588     0.0  0.138144  0.159794  0.004051  0.000000  0.266634   
19   0.505882     1.0  0.094845  0.207904  0.426835  0.000000  0.415591   
20   0.247059     1.0  0.189691  0.218213  0.134177  0.000000  0.627607   
21   0.270588     1.0  0.309278  0.273196  0.193418  0.000000  0.594340   
22   0.470588     1.0  0.162887  0.201031  0.000000  0.000000  0.020357   
23   0.247059     1.0  0.286598  0.300687  0.043038  0.000000  0.292453   
24   0.388235     1.0  0.278351  0.314433  0.000000  0.000000  0.937438   
25   0.435294     1.0  0.131959  0.225086  0.000000  0.000000  0.334161   
26   0.305882     1.0  0.101031  0.192440  0.009114  0.000000  0.041956   
27   0.282353     1.0  0.117526  0.199313  0.070886  0.000000  0.167825   
28   0.341176     1.0  0.134021  0.189003  0.336709  0.000000  0.283267   
29   0.376471     0.0  0.068041  0.190722  0.493165  0.000000  0.167577   
30   0.552941     1.0  0.094845  0.140893  0.000000  0.000000  0.653178   
31   0.564706     1.0  0.098969  0.137457  0.000000  0.000000  0.658640   
32   0.541176     1.0  0.125773  0.209622  0.027342  0.000000  0.579444   
33   0.435294     1.0  0.305155  0.376289  0.624304  0.000000  0.719215   
34   0.317647     1.0  0.092784  0.183849  0.077468  0.000000  0.116683   
35   0.294118     1.0  0.142268  0.189003  0.070380  0.000000  0.186941   
36   0.270588     1.0  0.278351  0.328179  0.189873  0.000000  0.635799   
37   0.517647     0.0  0.084536  0.190722  0.175696  0.000000  0.175273   
38   0.282353     1.0  0.197938  0.233677  0.019747  0.000000  0.035998   
39   0.682353     1.0  0.035052  0.128866  0.000000  0.000000  0.616435   
40   0.670588     1.0  0.098969  0.135739  0.158481  0.000000  0.198858   
41   0.611765     1.0  0.200000  0.197595  0.000000  0.000000  0.000000   
42   0.423529     0.0  0.088660  0.132302  0.299241  0.000000  0.564796   
43   0.341176     1.0  0.127835  0.158076  0.000000  0.000000  0.087885   
44   0.282353     1.0  0.191753  0.269759  0.099747  0.000000  0.386792   
45   0.270588     1.0  0.181443  0.329897  0.017722  0.000000  0.301142   
46   0.364706     1.0  0.119588  0.192440  0.026835  0.000000  0.285750   
47   0.682353     0.0  0.070103  0.139175  0.070380  0.000000  0.356504   
48   0.282353     1.0  0.107216  0.182131  0.272405  0.000000  0.616187   
49   0.552941     1.0  0.160825  0.228522  0.013165  0.000000  0.252731   
50   0.294118     1.0  0.241237  0.281787  0.163038  0.000000  0.838630   
51   0.270588     1.0  0.121649  0.189003  0.008101  0.000000  0.146226   
52   0.400000     1.0  0.127835  

In [10]:
X_SAN = df_norm_data_san.loc[:, features_indexes].values

X_SAN

array([[0.31764706, 1.        , 0.08865979, ..., 0.32054572, 0.22520155,
        0.23883212],
       [0.34117647, 1.        , 0.12989691, ..., 0.32325989, 0.22498305,
        0.23906396],
       [0.29411765, 1.        , 0.1257732 , ..., 0.30864185, 0.22715232,
        0.23753583],
       ...,
       [0.55294118, 0.        , 0.09896907, ..., 0.32318753, 0.22498751,
        0.23900893],
       [0.57647059, 0.        , 0.08865979, ..., 0.32951793, 0.23052265,
        0.21166397],
       [0.4       , 0.        , 0.09278351, ..., 0.32326295, 0.22498572,
        0.23902321]])

In [12]:
distances_san = np.array([[-1,-1,-1]])

for i in range(101):
    for j in range(i+1,101):
            #print(str(i)+' '+str(j))
            sum_sq = np.sum(np.square(X_SAN[i] - X_SAN[j]))
            distance = np.sqrt(sum_sq)
            distances_san = np.append(distances_san, [[i,j,distance]], axis=0)

distances_san


array([[ -1.        ,  -1.        ,  -1.        ],
       [  0.        ,   1.        ,   1.23841825],
       [  0.        ,   2.        ,   1.106123  ],
       ...,
       [ 98.        ,  99.        ,   0.4778331 ],
       [ 98.        , 100.        ,   0.18363049],
       [ 99.        , 100.        ,   0.57169941]])

In [13]:
distances_san = distances_san[distances_san[:,2].argsort()]

distances_san

array([[-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.00000000e+01,  3.10000000e+01,  1.54334100e-02],
       [ 2.10000000e+01,  3.60000000e+01,  9.23036084e-02],
       ...,
       [ 7.80000000e+01,  9.20000000e+01,  1.69560913e+00],
       [ 2.40000000e+01,  2.90000000e+01,  1.70635752e+00],
       [ 3.30000000e+01,  9.20000000e+01,  1.74890401e+00]])

# Parei aqui - Calcular as novas amostras artificiais para chegar em 200 instancias

In [14]:
X_SAN_AUGM = X_SAN.copy()

X_SAN_AUGM

array([[0.31764706, 1.        , 0.08865979, ..., 0.32054572, 0.22520155,
        0.23883212],
       [0.34117647, 1.        , 0.12989691, ..., 0.32325989, 0.22498305,
        0.23906396],
       [0.29411765, 1.        , 0.1257732 , ..., 0.30864185, 0.22715232,
        0.23753583],
       ...,
       [0.55294118, 0.        , 0.09896907, ..., 0.32318753, 0.22498751,
        0.23900893],
       [0.57647059, 0.        , 0.08865979, ..., 0.32951793, 0.23052265,
        0.21166397],
       [0.4       , 0.        , 0.09278351, ..., 0.32326295, 0.22498572,
        0.23902321]])

In [16]:
const_lambda = 0.5

for i in range(1,100):
    #print(str(i))
    #print(distances_san[i])
    #print(int(distances_san[i][0]))
    #print(int(distances_san[i][1]))
    nova_amostra = ((X_SAN[int(distances_san[i][0])] - X_SAN[int(distances_san[i][1])]) * const_lambda) + X_SAN[int(distances_san[i][1])]
    #print(nova_amostra)
    X_SAN_AUGM = np.append(X_SAN_AUGM, [nova_amostra], axis=0)

In [17]:
X_SAN_AUGM

array([[0.31764706, 1.        , 0.08865979, ..., 0.32054572, 0.22520155,
        0.23883212],
       [0.34117647, 1.        , 0.12989691, ..., 0.32325989, 0.22498305,
        0.23906396],
       [0.29411765, 1.        , 0.1257732 , ..., 0.30864185, 0.22715232,
        0.23753583],
       ...,
       [0.24117647, 1.        , 0.18041237, ..., 0.32164796, 0.22491012,
        0.23902338],
       [0.32941176, 1.        , 0.16082474, ..., 0.32322443, 0.22495496,
        0.23901247],
       [0.29411765, 1.        , 0.10927835, ..., 0.31811327, 0.22570597,
        0.2434789 ]])

In [19]:
df_norm_augm_data_san = pd.DataFrame(X_SAN_AUGM, columns = features_indexes)
df_norm_augm_data_san.head(500)

idade  genero    volume     massa      edl1      edl2      edl3  \
0    0.317647     1.0  0.088660  0.163230  0.004051  0.000000  0.145233   
1    0.341176     1.0  0.129897  0.190722  0.243038  0.000000  0.705065   
2    0.294118     1.0  0.125773  0.243986  0.361519  0.000000  0.439921   
3    0.588235     1.0  0.154639  0.158076  0.000000  0.000000  0.121648   
4    0.635294     1.0  0.076289  0.099656  0.040000  0.000000  0.524081   
5    0.388235     0.0  0.080412  0.151203  0.058228  0.000000  0.116187   
6    0.647059     1.0  0.253608  0.178694  0.018228  0.000000  0.279295   
7    0.423529     1.0  0.164948  0.211340  0.092152  0.000000  0.142751   
8    0.341176     1.0  0.096907  0.161512  0.368101  0.000000  0.154667   
9    0.588235     1.0  0.078351  0.113402  0.000000  0.000000  0.009682   
10   0.388235     1.0  0.152577  0.171821  0.145823  0.000000  0.210030   
11   0.376471     1.0  0.164948  0.211340  0.215696  0.000000  0.436197   
12   0.341176     1.0  0.179381  0.231959  0.193418  0.000000  0.251986   
13   0.388235     1.0  0.259794  0.250859  0.000000  0.000000  0.216981   
14   0.764706     1.0  0.088660  0.168385  0.044557  0.000000  0.299652   
15   0.411765     1.0  0.107216  0.159794  0.108354  0.000000  0.119166   
16   0.258824     1.0  0.177320  0.269759  0.022785  0.000000  0.579940   
17   0.447059     0.0  0.107216  0.137457  0.227342  0.000000  0.292453   
18   0.670588     0.0  0.138144  0.159794  0.004051  0.000000  0.266634   
19   0.505882     1.0  0.094845  0.207904  0.426835  0.000000  0.415591   
20   0.247059     1.0  0.189691  0.218213  0.134177  0.000000  0.627607   
21   0.270588     1.0  0.309278  0.273196  0.193418  0.000000  0.594340   
22   0.470588     1.0  0.162887  0.201031  0.000000  0.000000  0.020357   
23   0.247059     1.0  0.286598  0.300687  0.043038  0.000000  0.292453   
24   0.388235     1.0  0.278351  0.314433  0.000000  0.000000  0.937438   
25   0.435294     1.0  0.131959  0.225086  0.000000  0.000000  0.334161   
26   0.305882     1.0  0.101031  0.192440  0.009114  0.000000  0.041956   
27   0.282353     1.0  0.117526  0.199313  0.070886  0.000000  0.167825   
28   0.341176     1.0  0.134021  0.189003  0.336709  0.000000  0.283267   
29   0.376471     0.0  0.068041  0.190722  0.493165  0.000000  0.167577   
30   0.552941     1.0  0.094845  0.140893  0.000000  0.000000  0.653178   
31   0.564706     1.0  0.098969  0.137457  0.000000  0.000000  0.658640   
32   0.541176     1.0  0.125773  0.209622  0.027342  0.000000  0.579444   
33   0.435294     1.0  0.305155  0.376289  0.624304  0.000000  0.719215   
34   0.317647     1.0  0.092784  0.183849  0.077468  0.000000  0.116683   
35   0.294118     1.0  0.142268  0.189003  0.070380  0.000000  0.186941   
36   0.270588     1.0  0.278351  0.328179  0.189873  0.000000  0.635799   
37   0.517647     0.0  0.084536  0.190722  0.175696  0.000000  0.175273   
38   0.282353     1.0  0.197938  0.233677  0.019747  0.000000  0.035998   
39   0.682353     1.0  0.035052  0.128866  0.000000  0.000000  0.616435   
40   0.670588     1.0  0.098969  0.135739  0.158481  0.000000  0.198858   
41   0.611765     1.0  0.200000  0.197595  0.000000  0.000000  0.000000   
42   0.423529     0.0  0.088660  0.132302  0.299241  0.000000  0.564796   
43   0.341176     1.0  0.127835  0.158076  0.000000  0.000000  0.087885   
44   0.282353     1.0  0.191753  0.269759  0.099747  0.000000  0.386792   
45   0.270588     1.0  0.181443  0.329897  0.017722  0.000000  0.301142   
46   0.364706     1.0  0.119588  0.192440  0.026835  0.000000  0.285750   
47   0.682353     0.0  0.070103  0.139175  0.070380  0.000000  0.356504   
48   0.282353     1.0  0.107216  0.182131  0.272405  0.000000  0.616187   
49   0.552941     1.0  0.160825  0.228522  0.013165  0.000000  0.252731   
50   0.294118     1.0  0.241237  0.281787  0.163038  0.000000  0.838630   
51   0.270588     1.0  0.121649  0.189003  0.008101  0.000000  0.146226   
52   0.400000     1.0  0.127835  

In [20]:
df_norm_augm_data_san['target'] = 0
df_norm_augm_data_san.head(400)

idade  genero    volume     massa      edl1      edl2      edl3  \
0    0.317647     1.0  0.088660  0.163230  0.004051  0.000000  0.145233   
1    0.341176     1.0  0.129897  0.190722  0.243038  0.000000  0.705065   
2    0.294118     1.0  0.125773  0.243986  0.361519  0.000000  0.439921   
3    0.588235     1.0  0.154639  0.158076  0.000000  0.000000  0.121648   
4    0.635294     1.0  0.076289  0.099656  0.040000  0.000000  0.524081   
5    0.388235     0.0  0.080412  0.151203  0.058228  0.000000  0.116187   
6    0.647059     1.0  0.253608  0.178694  0.018228  0.000000  0.279295   
7    0.423529     1.0  0.164948  0.211340  0.092152  0.000000  0.142751   
8    0.341176     1.0  0.096907  0.161512  0.368101  0.000000  0.154667   
9    0.588235     1.0  0.078351  0.113402  0.000000  0.000000  0.009682   
10   0.388235     1.0  0.152577  0.171821  0.145823  0.000000  0.210030   
11   0.376471     1.0  0.164948  0.211340  0.215696  0.000000  0.436197   
12   0.341176     1.0  0.179381  0.231959  0.193418  0.000000  0.251986   
13   0.388235     1.0  0.259794  0.250859  0.000000  0.000000  0.216981   
14   0.764706     1.0  0.088660  0.168385  0.044557  0.000000  0.299652   
15   0.411765     1.0  0.107216  0.159794  0.108354  0.000000  0.119166   
16   0.258824     1.0  0.177320  0.269759  0.022785  0.000000  0.579940   
17   0.447059     0.0  0.107216  0.137457  0.227342  0.000000  0.292453   
18   0.670588     0.0  0.138144  0.159794  0.004051  0.000000  0.266634   
19   0.505882     1.0  0.094845  0.207904  0.426835  0.000000  0.415591   
20   0.247059     1.0  0.189691  0.218213  0.134177  0.000000  0.627607   
21   0.270588     1.0  0.309278  0.273196  0.193418  0.000000  0.594340   
22   0.470588     1.0  0.162887  0.201031  0.000000  0.000000  0.020357   
23   0.247059     1.0  0.286598  0.300687  0.043038  0.000000  0.292453   
24   0.388235     1.0  0.278351  0.314433  0.000000  0.000000  0.937438   
25   0.435294     1.0  0.131959  0.225086  0.000000  0.000000  0.334161   
26   0.305882     1.0  0.101031  0.192440  0.009114  0.000000  0.041956   
27   0.282353     1.0  0.117526  0.199313  0.070886  0.000000  0.167825   
28   0.341176     1.0  0.134021  0.189003  0.336709  0.000000  0.283267   
29   0.376471     0.0  0.068041  0.190722  0.493165  0.000000  0.167577   
30   0.552941     1.0  0.094845  0.140893  0.000000  0.000000  0.653178   
31   0.564706     1.0  0.098969  0.137457  0.000000  0.000000  0.658640   
32   0.541176     1.0  0.125773  0.209622  0.027342  0.000000  0.579444   
33   0.435294     1.0  0.305155  0.376289  0.624304  0.000000  0.719215   
34   0.317647     1.0  0.092784  0.183849  0.077468  0.000000  0.116683   
35   0.294118     1.0  0.142268  0.189003  0.070380  0.000000  0.186941   
36   0.270588     1.0  0.278351  0.328179  0.189873  0.000000  0.635799   
37   0.517647     0.0  0.084536  0.190722  0.175696  0.000000  0.175273   
38   0.282353     1.0  0.197938  0.233677  0.019747  0.000000  0.035998   
39   0.682353     1.0  0.035052  0.128866  0.000000  0.000000  0.616435   
40   0.670588     1.0  0.098969  0.135739  0.158481  0.000000  0.198858   
41   0.611765     1.0  0.200000  0.197595  0.000000  0.000000  0.000000   
42   0.423529     0.0  0.088660  0.132302  0.299241  0.000000  0.564796   
43   0.341176     1.0  0.127835  0.158076  0.000000  0.000000  0.087885   
44   0.282353     1.0  0.191753  0.269759  0.099747  0.000000  0.386792   
45   0.270588     1.0  0.181443  0.329897  0.017722  0.000000  0.301142   
46   0.364706     1.0  0.119588  0.192440  0.026835  0.000000  0.285750   
47   0.682353     0.0  0.070103  0.139175  0.070380  0.000000  0.356504   
48   0.282353     1.0  0.107216  0.182131  0.272405  0.000000  0.616187   
49   0.552941     1.0  0.160825  0.228522  0.013165  0.000000  0.252731   
50   0.294118     1.0  0.241237  0.281787  0.163038  0.000000  0.838630   
51   0.270588     1.0  0.121649  0.189003  0.008101  0.000000  0.146226   
52   0.400000     1.0  0.127835  

In [21]:
df_norm_augm_data_san.to_csv("../Database/df_database_dados_normalizados_aumentados_minmax_san.csv", index = False)