informações sobre as amostras originais:

index 0 a 100 - SAN - 101

index 101 a 283 - CMH - 183

index 284 a 399 - CMD - 116


In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)

In [3]:
df_norm_data = pd.read_csv("../Database/df_database_dados_normalizados_minmax.csv")
df_norm_data.head()

idade  genero    volume     massa      edl1  edl2      edl3  edl4  \
0  0.317647     1.0  0.088660  0.163230  0.004051   0.0  0.145233   0.0   
1  0.341176     1.0  0.129897  0.190722  0.243038   0.0  0.705065   0.0   
2  0.294118     1.0  0.125773  0.243986  0.361519   0.0  0.439921   0.0   
3  0.588235     1.0  0.154639  0.158076  0.000000   0.0  0.121648   0.0   
4  0.635294     1.0  0.076289  0.099656  0.040000   0.0  0.524081   0.0   

       edl5  edl6      edl7  edl8    hough1  hough2    hough3  hough4  \
0  0.204617   0.0  0.541572   0.0  0.003559     0.0  0.126543     0.0   
1  0.000000   0.0  0.000000   0.0  0.227758     0.0  0.695988     0.0   
2  0.024257   0.0  0.144177   0.0  0.387900     0.0  0.484568     0.0   
3  0.031690   0.0  0.407845   0.0  0.000000     0.0  0.097222     0.0   
4  0.000000   0.0  0.064365   0.0  0.032028     0.0  0.495370     0.0   

     hough5  hough6    hough7  hough8   spharm1   spharm2   spharm3   spharm4  \
0  0.187845     0.0  0.641855     0.0  0.674581  0.472682  0.960090  0.615620   
1  0.000000     0.0  0.000000     0.0  0.730882  0.472890  0.960034  0.614617   
2  0.030387     0.0  0.167206     0.0  0.732323  1.000000  0.990207  0.620600   
3  0.024862     0.0  0.436893     0.0  0.731000  0.472816  0.960065  0.615284   
4  0.000000     0.0  0.061489     0.0  0.725301  0.472820  0.960034  0.615304   

    spharm5   spharm6   spharm7   spharm8  target  
0  0.512404  0.320546  0.225202  0.238832       0  
1  0.511467  0.323260  0.224983  0.239064       0  
2  0.551338  0.308642  0.227152  0.237536       0  
3  0.550603  0.323264  0.225098  0.239055       0  
4  0.509081  0.323261  0.224991  0.239020       0

In [4]:
features_indexes = df_norm_data.columns[0:-1]
print(features_indexes)

Index(['idade', 'genero', 'volume', 'massa', 'edl1', 'edl2', 'edl3', 'edl4',
       'edl5', 'edl6', 'edl7', 'edl8', 'hough1', 'hough2', 'hough3', 'hough4',
       'hough5', 'hough6', 'hough7', 'hough8', 'spharm1', 'spharm2', 'spharm3',
       'spharm4', 'spharm5', 'spharm6', 'spharm7', 'spharm8'],
      dtype='object')


In [5]:
df_norm_data_cmh = df_norm_data[df_norm_data['target']==2]
df_norm_data_cmh

idade  genero    volume     massa      edl1      edl2      edl3  \
101  0.623529     1.0  0.263918  0.142612  0.000000  0.000000  0.050645   
102  0.776471     1.0  0.430928  0.134021  0.000000  0.000000  0.272344   
103  0.329412     0.0  0.329897  0.139175  0.466835  0.000000  0.189176   
104  0.752941     0.0  0.348454  0.163230  0.092152  0.000000  0.314548   
105  0.317647     1.0  0.280412  0.156357  0.000000  0.000000  0.029543   
106  0.541176     0.0  0.459794  0.118557  0.100759  0.000000  0.212016   
107  0.341176     0.0  0.183505  0.113402  0.149367  0.000000  0.239573   
108  0.752941     1.0  0.158763  0.156357  0.039494  0.000000  0.408640   
109  0.317647     0.0  0.136082  0.134021  0.051646  0.000000  0.390765   
110  0.211765     1.0  0.195876  0.025773  0.000000  0.000000  0.000000   
111  0.564706     0.0  0.602062  0.135739  0.117975  0.000000  0.245780   
112  0.411765     1.0  0.369072  0.094502  0.000000  0.000000  0.000000   
113  0.705882     1.0  0.336082  0.001718  0.000000  0.000000  0.000000   
114  0.411765     0.0  0.385567  0.068729  0.206582  0.000000  0.566038   
115  0.294118     0.0  0.241237  0.085911  0.414177  0.000000  0.125124   
116  0.647059     1.0  0.696907  0.089347  0.000000  0.000000  0.127607   
117  0.705882     1.0  0.144330  0.194158  0.000000  0.000000  0.377110   
118  0.917647     0.0  0.245361  0.158076  0.158987  0.000000  0.590864   
119  0.282353     1.0  0.173196  0.206186  0.000000  0.000000  0.013406   
120  0.717647     1.0  0.154639  0.209622  0.000000  0.000000  0.020109   
121  0.235294     1.0  0.472165  0.128866  0.000000  0.000000  0.017378   
122  0.729412     0.0  0.092784  0.096220  0.149873  0.000000  0.130089   
123  0.717647     0.0  0.200000  0.151203  0.157975  0.000000  0.270854   
124  0.423529     1.0  0.204124  0.242268  0.018228  0.000000  0.310079   
125  0.341176     0.0  0.074227  0.099656  0.020759  0.000000  0.116187   
126  0.505882     1.0  0.369072  0.276632  0.000000  0.000000  0.146723   
127  0.670588     1.0  0.121649  0.094502  0.000000  0.000000  0.026068   
128  0.576471     1.0  0.261856  0.085911  0.000000  0.000000  0.020109   
129  0.505882     0.0  0.222680  0.199313  0.040000  0.000000  0.673535   
130  0.423529     1.0  0.282474  0.207904  0.228354  0.000000  0.758689   
131  0.564706     0.0  0.228866  0.166667  0.000000  0.000000  0.222939   
132  0.647059     0.0  0.113402  0.146048  0.000000  0.000000  0.069513   
133  0.423529     1.0  0.461856  0.161512  0.243038  0.000000  0.230884   
134  0.658824     0.0  0.226804  0.178694  0.000000  0.000000  0.027557   
135  0.670588     1.0  0.389691  0.230241  0.000000  0.000000  0.027557   
136  0.752941     1.0  0.214433  0.259450  0.000000  0.000000  0.000000   
137  0.376471     1.0  0.329897  0.037801  0.000000  0.000000  0.039225   
138  0.705882     1.0  0.377320  0.075601  0.071899  0.000000  0.241559   
139  0.282353     0.0  0.107216  0.065292  0.000000  0.000000  0.000000   
140  0.882353     0.0  0.070103  0.101375  0.000000  0.000000  0.000000   
141  0.388235     0.0  0.113402  0.242268  0.000000  0.000000  0.004965   
142  0.635294     1.0  0.272165  0.316151  0.000000  0.000000  0.954816   
143  0.411765     1.0  0.179381  0.252577  0.000000  0.000000  0.298411   
144  0.564706     1.0  0.385567  0.168385  0.000000  0.000000  0.226415   
145  0.741176     0.0  0.098969  0.134021  0.000000  0.000000  0.028302   
146  0.352941     1.0  0.272165  0.030928  0.009114  0.000000  0.124876   
147  0.729412     1.0  0.301031  0.113402  0.000000  0.000000  0.114449   
148  0.376471     0.0  0.470103  0.142612  0.000000  0.000000  0.000000   
149  0.717647     1.0  0.509278  0.176976  0.000000  0.000000  0.515392   
150  0.247059     1.0  0.416495  0.197595  0.000000  0.000000  0.000000   
151  0.482353     1.0  0.595876  0.149485  0.185823  0.000000  0.456058   
152  0.305882     1.0  0.369072  0.175258  0.000000  0.000000  0.186693   
153  0.082353     0.0  0.546392  

In [6]:
X_CMH = df_norm_data_cmh.loc[:, features_indexes].values

X_CMH

array([[0.62352941, 1.        , 0.26391753, ..., 0.32326436, 0.22504744,
        0.2390419 ],
       [0.77647059, 1.        , 0.43092784, ..., 0.32326173, 0.22507193,
        0.23902029],
       [0.32941176, 0.        , 0.32989691, ..., 0.32326394, 0.21141018,
        0.18907368],
       ...,
       [0.57647059, 1.        , 0.07010309, ..., 0.3227768 , 0.2250056 ,
        0.23984887],
       [0.15294118, 0.        , 0.2371134 , ..., 0.32226585, 0.38138521,
        0.28323024],
       [0.64705882, 1.        , 0.33402062, ..., 0.32326147, 0.22495098,
        0.23902216]])

In [7]:
distances_cmh = np.array([[-1,-1,-1]])

for i in range(183):
    for j in range(i+1,183):
            #print(str(i)+' '+str(j))
            sum_sq = np.sum(np.square(X_CMH[i] - X_CMH[j]))
            distance = np.sqrt(sum_sq)
            distances_cmh = np.append(distances_cmh, [[i,j,distance]], axis=0)

distances_cmh


array([[ -1.        ,  -1.        ,  -1.        ],
       [  0.        ,   1.        ,   0.43554571],
       [  0.        ,   2.        ,   1.40980337],
       ...,
       [180.        , 181.        ,   1.32719794],
       [180.        , 182.        ,   0.53321543],
       [181.        , 182.        ,   1.56138986]])

In [8]:
distances_cmh = distances_cmh[distances_cmh[:,2].argsort()]

distances_cmh

array([[-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 6.20000000e+01,  1.22000000e+02,  6.82386155e-02],
       [ 8.20000000e+01,  1.79000000e+02,  9.06172991e-02],
       ...,
       [ 9.40000000e+01,  1.03000000e+02,  2.56605807e+00],
       [ 3.90000000e+01,  9.40000000e+01,  2.57522122e+00],
       [ 2.10000000e+01,  9.40000000e+01,  2.67821576e+00]])

# Parei aqui - Calcular as novas amostras artificiais para chegar em 200 instancias

In [9]:
X_CMH_AUGM = X_CMH.copy()

X_CMH_AUGM

array([[0.62352941, 1.        , 0.26391753, ..., 0.32326436, 0.22504744,
        0.2390419 ],
       [0.77647059, 1.        , 0.43092784, ..., 0.32326173, 0.22507193,
        0.23902029],
       [0.32941176, 0.        , 0.32989691, ..., 0.32326394, 0.21141018,
        0.18907368],
       ...,
       [0.57647059, 1.        , 0.07010309, ..., 0.3227768 , 0.2250056 ,
        0.23984887],
       [0.15294118, 0.        , 0.2371134 , ..., 0.32226585, 0.38138521,
        0.28323024],
       [0.64705882, 1.        , 0.33402062, ..., 0.32326147, 0.22495098,
        0.23902216]])

In [10]:
const_lambda = 0.5

for i in range(1,18):
    #print(str(i))
    #print(distances_cmh[i])
    #print(int(distances_cmh[i][0]))
    #print(int(distances_cmh[i][1]))
    nova_amostra = ((X_CMH[int(distances_cmh[i][0])] - X_CMH[int(distances_cmh[i][1])]) * const_lambda) + X_CMH[int(distances_cmh[i][1])]
    #print(nova_amostra)
    X_CMH_AUGM = np.append(X_CMH_AUGM, [nova_amostra], axis=0)

In [11]:
X_CMH_AUGM

array([[0.62352941, 1.        , 0.26391753, ..., 0.32326436, 0.22504744,
        0.2390419 ],
       [0.77647059, 1.        , 0.43092784, ..., 0.32326173, 0.22507193,
        0.23902029],
       [0.32941176, 0.        , 0.32989691, ..., 0.32326394, 0.21141018,
        0.18907368],
       ...,
       [0.54117647, 1.        , 0.3185567 , ..., 0.32326162, 0.22497758,
        0.23902633],
       [0.54117647, 1.        , 0.23917526, ..., 0.32326511, 0.22497677,
        0.23910286],
       [0.71176471, 1.        , 0.34020619, ..., 0.32330325, 0.22490635,
        0.23932507]])

In [12]:
df_norm_augm_data_cmh = pd.DataFrame(X_CMH_AUGM, columns = features_indexes)
df_norm_augm_data_cmh.head(500)

idade  genero    volume     massa      edl1      edl2      edl3  \
0    0.623529     1.0  0.263918  0.142612  0.000000  0.000000  0.050645   
1    0.776471     1.0  0.430928  0.134021  0.000000  0.000000  0.272344   
2    0.329412     0.0  0.329897  0.139175  0.466835  0.000000  0.189176   
3    0.752941     0.0  0.348454  0.163230  0.092152  0.000000  0.314548   
4    0.317647     1.0  0.280412  0.156357  0.000000  0.000000  0.029543   
5    0.541176     0.0  0.459794  0.118557  0.100759  0.000000  0.212016   
6    0.341176     0.0  0.183505  0.113402  0.149367  0.000000  0.239573   
7    0.752941     1.0  0.158763  0.156357  0.039494  0.000000  0.408640   
8    0.317647     0.0  0.136082  0.134021  0.051646  0.000000  0.390765   
9    0.211765     1.0  0.195876  0.025773  0.000000  0.000000  0.000000   
10   0.564706     0.0  0.602062  0.135739  0.117975  0.000000  0.245780   
11   0.411765     1.0  0.369072  0.094502  0.000000  0.000000  0.000000   
12   0.705882     1.0  0.336082  0.001718  0.000000  0.000000  0.000000   
13   0.411765     0.0  0.385567  0.068729  0.206582  0.000000  0.566038   
14   0.294118     0.0  0.241237  0.085911  0.414177  0.000000  0.125124   
15   0.647059     1.0  0.696907  0.089347  0.000000  0.000000  0.127607   
16   0.705882     1.0  0.144330  0.194158  0.000000  0.000000  0.377110   
17   0.917647     0.0  0.245361  0.158076  0.158987  0.000000  0.590864   
18   0.282353     1.0  0.173196  0.206186  0.000000  0.000000  0.013406   
19   0.717647     1.0  0.154639  0.209622  0.000000  0.000000  0.020109   
20   0.235294     1.0  0.472165  0.128866  0.000000  0.000000  0.017378   
21   0.729412     0.0  0.092784  0.096220  0.149873  0.000000  0.130089   
22   0.717647     0.0  0.200000  0.151203  0.157975  0.000000  0.270854   
23   0.423529     1.0  0.204124  0.242268  0.018228  0.000000  0.310079   
24   0.341176     0.0  0.074227  0.099656  0.020759  0.000000  0.116187   
25   0.505882     1.0  0.369072  0.276632  0.000000  0.000000  0.146723   
26   0.670588     1.0  0.121649  0.094502  0.000000  0.000000  0.026068   
27   0.576471     1.0  0.261856  0.085911  0.000000  0.000000  0.020109   
28   0.505882     0.0  0.222680  0.199313  0.040000  0.000000  0.673535   
29   0.423529     1.0  0.282474  0.207904  0.228354  0.000000  0.758689   
30   0.564706     0.0  0.228866  0.166667  0.000000  0.000000  0.222939   
31   0.647059     0.0  0.113402  0.146048  0.000000  0.000000  0.069513   
32   0.423529     1.0  0.461856  0.161512  0.243038  0.000000  0.230884   
33   0.658824     0.0  0.226804  0.178694  0.000000  0.000000  0.027557   
34   0.670588     1.0  0.389691  0.230241  0.000000  0.000000  0.027557   
35   0.752941     1.0  0.214433  0.259450  0.000000  0.000000  0.000000   
36   0.376471     1.0  0.329897  0.037801  0.000000  0.000000  0.039225   
37   0.705882     1.0  0.377320  0.075601  0.071899  0.000000  0.241559   
38   0.282353     0.0  0.107216  0.065292  0.000000  0.000000  0.000000   
39   0.882353     0.0  0.070103  0.101375  0.000000  0.000000  0.000000   
40   0.388235     0.0  0.113402  0.242268  0.000000  0.000000  0.004965   
41   0.635294     1.0  0.272165  0.316151  0.000000  0.000000  0.954816   
42   0.411765     1.0  0.179381  0.252577  0.000000  0.000000  0.298411   
43   0.564706     1.0  0.385567  0.168385  0.000000  0.000000  0.226415   
44   0.741176     0.0  0.098969  0.134021  0.000000  0.000000  0.028302   
45   0.352941     1.0  0.272165  0.030928  0.009114  0.000000  0.124876   
46   0.729412     1.0  0.301031  0.113402  0.000000  0.000000  0.114449   
47   0.376471     0.0  0.470103  0.142612  0.000000  0.000000  0.000000   
48   0.717647     1.0  0.509278  0.176976  0.000000  0.000000  0.515392   
49   0.247059     1.0  0.416495  0.197595  0.000000  0.000000  0.000000   
50   0.482353     1.0  0.595876  0.149485  0.185823  0.000000  0.456058   
51   0.305882     1.0  0.369072  0.175258  0.000000  0.000000  0.186693   
52   0.082353     0.0  0.546392  

In [13]:
df_norm_augm_data_cmh['target'] = 2
df_norm_augm_data_cmh.head(400)

idade  genero    volume     massa      edl1      edl2      edl3  \
0    0.623529     1.0  0.263918  0.142612  0.000000  0.000000  0.050645   
1    0.776471     1.0  0.430928  0.134021  0.000000  0.000000  0.272344   
2    0.329412     0.0  0.329897  0.139175  0.466835  0.000000  0.189176   
3    0.752941     0.0  0.348454  0.163230  0.092152  0.000000  0.314548   
4    0.317647     1.0  0.280412  0.156357  0.000000  0.000000  0.029543   
5    0.541176     0.0  0.459794  0.118557  0.100759  0.000000  0.212016   
6    0.341176     0.0  0.183505  0.113402  0.149367  0.000000  0.239573   
7    0.752941     1.0  0.158763  0.156357  0.039494  0.000000  0.408640   
8    0.317647     0.0  0.136082  0.134021  0.051646  0.000000  0.390765   
9    0.211765     1.0  0.195876  0.025773  0.000000  0.000000  0.000000   
10   0.564706     0.0  0.602062  0.135739  0.117975  0.000000  0.245780   
11   0.411765     1.0  0.369072  0.094502  0.000000  0.000000  0.000000   
12   0.705882     1.0  0.336082  0.001718  0.000000  0.000000  0.000000   
13   0.411765     0.0  0.385567  0.068729  0.206582  0.000000  0.566038   
14   0.294118     0.0  0.241237  0.085911  0.414177  0.000000  0.125124   
15   0.647059     1.0  0.696907  0.089347  0.000000  0.000000  0.127607   
16   0.705882     1.0  0.144330  0.194158  0.000000  0.000000  0.377110   
17   0.917647     0.0  0.245361  0.158076  0.158987  0.000000  0.590864   
18   0.282353     1.0  0.173196  0.206186  0.000000  0.000000  0.013406   
19   0.717647     1.0  0.154639  0.209622  0.000000  0.000000  0.020109   
20   0.235294     1.0  0.472165  0.128866  0.000000  0.000000  0.017378   
21   0.729412     0.0  0.092784  0.096220  0.149873  0.000000  0.130089   
22   0.717647     0.0  0.200000  0.151203  0.157975  0.000000  0.270854   
23   0.423529     1.0  0.204124  0.242268  0.018228  0.000000  0.310079   
24   0.341176     0.0  0.074227  0.099656  0.020759  0.000000  0.116187   
25   0.505882     1.0  0.369072  0.276632  0.000000  0.000000  0.146723   
26   0.670588     1.0  0.121649  0.094502  0.000000  0.000000  0.026068   
27   0.576471     1.0  0.261856  0.085911  0.000000  0.000000  0.020109   
28   0.505882     0.0  0.222680  0.199313  0.040000  0.000000  0.673535   
29   0.423529     1.0  0.282474  0.207904  0.228354  0.000000  0.758689   
30   0.564706     0.0  0.228866  0.166667  0.000000  0.000000  0.222939   
31   0.647059     0.0  0.113402  0.146048  0.000000  0.000000  0.069513   
32   0.423529     1.0  0.461856  0.161512  0.243038  0.000000  0.230884   
33   0.658824     0.0  0.226804  0.178694  0.000000  0.000000  0.027557   
34   0.670588     1.0  0.389691  0.230241  0.000000  0.000000  0.027557   
35   0.752941     1.0  0.214433  0.259450  0.000000  0.000000  0.000000   
36   0.376471     1.0  0.329897  0.037801  0.000000  0.000000  0.039225   
37   0.705882     1.0  0.377320  0.075601  0.071899  0.000000  0.241559   
38   0.282353     0.0  0.107216  0.065292  0.000000  0.000000  0.000000   
39   0.882353     0.0  0.070103  0.101375  0.000000  0.000000  0.000000   
40   0.388235     0.0  0.113402  0.242268  0.000000  0.000000  0.004965   
41   0.635294     1.0  0.272165  0.316151  0.000000  0.000000  0.954816   
42   0.411765     1.0  0.179381  0.252577  0.000000  0.000000  0.298411   
43   0.564706     1.0  0.385567  0.168385  0.000000  0.000000  0.226415   
44   0.741176     0.0  0.098969  0.134021  0.000000  0.000000  0.028302   
45   0.352941     1.0  0.272165  0.030928  0.009114  0.000000  0.124876   
46   0.729412     1.0  0.301031  0.113402  0.000000  0.000000  0.114449   
47   0.376471     0.0  0.470103  0.142612  0.000000  0.000000  0.000000   
48   0.717647     1.0  0.509278  0.176976  0.000000  0.000000  0.515392   
49   0.247059     1.0  0.416495  0.197595  0.000000  0.000000  0.000000   
50   0.482353     1.0  0.595876  0.149485  0.185823  0.000000  0.456058   
51   0.305882     1.0  0.369072  0.175258  0.000000  0.000000  0.186693   
52   0.082353     0.0  0.546392  

In [14]:
df_norm_augm_data_cmh.to_csv("../Database/df_database_dados_normalizados_aumentados_minmax_cmh.csv", index = False)