informações sobre as amostras originais:

index 0 a 100 - SAN - 101

index 101 a 283 - CMH - 183

index 284 a 399 - CMD - 116


In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)

In [3]:
df_norm_data = pd.read_csv("../Database/df_database_dados_normalizados_minmax.csv")
df_norm_data.head()

idade  genero    volume     massa      edl1  edl2      edl3  edl4  \
0  0.317647     1.0  0.088660  0.163230  0.004051   0.0  0.145233   0.0   
1  0.341176     1.0  0.129897  0.190722  0.243038   0.0  0.705065   0.0   
2  0.294118     1.0  0.125773  0.243986  0.361519   0.0  0.439921   0.0   
3  0.588235     1.0  0.154639  0.158076  0.000000   0.0  0.121648   0.0   
4  0.635294     1.0  0.076289  0.099656  0.040000   0.0  0.524081   0.0   

       edl5  edl6      edl7  edl8    hough1  hough2    hough3  hough4  \
0  0.204617   0.0  0.541572   0.0  0.003559     0.0  0.126543     0.0   
1  0.000000   0.0  0.000000   0.0  0.227758     0.0  0.695988     0.0   
2  0.024257   0.0  0.144177   0.0  0.387900     0.0  0.484568     0.0   
3  0.031690   0.0  0.407845   0.0  0.000000     0.0  0.097222     0.0   
4  0.000000   0.0  0.064365   0.0  0.032028     0.0  0.495370     0.0   

     hough5  hough6    hough7  hough8   spharm1   spharm2   spharm3   spharm4  \
0  0.187845     0.0  0.641855     0.0  0.674581  0.472682  0.960090  0.615620   
1  0.000000     0.0  0.000000     0.0  0.730882  0.472890  0.960034  0.614617   
2  0.030387     0.0  0.167206     0.0  0.732323  1.000000  0.990207  0.620600   
3  0.024862     0.0  0.436893     0.0  0.731000  0.472816  0.960065  0.615284   
4  0.000000     0.0  0.061489     0.0  0.725301  0.472820  0.960034  0.615304   

    spharm5   spharm6   spharm7   spharm8  target  
0  0.512404  0.320546  0.225202  0.238832       0  
1  0.511467  0.323260  0.224983  0.239064       0  
2  0.551338  0.308642  0.227152  0.237536       0  
3  0.550603  0.323264  0.225098  0.239055       0  
4  0.509081  0.323261  0.224991  0.239020       0

In [4]:
features_indexes = df_norm_data.columns[0:-1]
print(features_indexes)

Index(['idade', 'genero', 'volume', 'massa', 'edl1', 'edl2', 'edl3', 'edl4',
       'edl5', 'edl6', 'edl7', 'edl8', 'hough1', 'hough2', 'hough3', 'hough4',
       'hough5', 'hough6', 'hough7', 'hough8', 'spharm1', 'spharm2', 'spharm3',
       'spharm4', 'spharm5', 'spharm6', 'spharm7', 'spharm8'],
      dtype='object')


In [5]:
df_norm_data_cmd = df_norm_data[df_norm_data['target']==1]
df_norm_data_cmd

idade  genero    volume     massa      edl1  edl2      edl3      edl4  \
284  0.588235     1.0  0.235052  0.146048  0.103797   0.0  0.191410  0.000000   
285  0.552941     0.0  0.136082  0.159794  0.097215   0.0  0.422542  0.000000   
286  0.835294     1.0  0.253608  0.223368  0.086582   0.0  0.361470  0.000000   
287  0.964706     1.0  0.216495  0.357388  0.000000   0.0  0.282274  0.000000   
288  0.517647     1.0  0.426804  0.379725  0.000000   0.0  0.433217  0.000000   
289  0.835294     1.0  0.315464  0.785223  0.137722   0.0  0.379841  0.000000   
290  0.435294     1.0  0.552577  0.773196  0.259241   0.0  0.332423  0.000000   
291  0.682353     0.0  0.222680  0.164948  0.071392   0.0  0.206306  0.000000   
292  0.364706     1.0  0.113402  0.171821  0.154430   0.0  0.450348  0.181569   
293  0.658824     1.0  0.290722  0.580756  0.014684   0.0  0.615194  0.000000   
294  0.741176     1.0  0.278351  0.271478  0.737215   0.0  0.658391  0.000000   
295  0.847059     1.0  0.513402  0.316151  0.000000   0.0  0.559086  0.000000   
296  1.000000     1.0  0.111340  0.130584  0.000000   0.0  0.536743  0.036496   
297  0.764706     1.0  0.284536  0.396907  0.013671   0.0  0.102284  0.000000   
298  0.611765     1.0  0.138144  0.073883  0.009114   0.0  0.018371  0.000000   
299  0.517647     0.0  0.059794  0.109966  0.000000   0.0  0.133813  0.000000   
300  0.670588     1.0  0.447423  0.847079  0.089620   0.0  0.456058  0.000000   
301  0.847059     1.0  0.177320  0.237113  0.000000   0.0  0.000000  0.000000   
302  0.776471     1.0  0.131959  0.199313  0.000000   0.0  0.000000  0.000000   
303  0.517647     1.0  0.241237  0.372852  0.637975   0.0  0.693893  0.000000   
304  0.352941     1.0  0.362887  0.046392  0.080000   0.0  0.235353  0.000000   
305  0.600000     1.0  0.468041  0.613402  0.108861   0.0  0.665839  0.000000   
306  0.447059     1.0  0.606186  1.000000  0.149873   0.0  0.502731  0.000000   
307  0.729412     1.0  0.123711  0.206186  0.000000   0.0  0.188183  0.000000   
308  0.882353     1.0  0.226804  0.178694  0.000000   0.0  0.188183  0.000000   
309  0.517647     1.0  0.169072  0.240550  0.564051   0.0  0.415839  0.000000   
310  0.647059     0.0  0.175258  0.462199  0.136709   0.0  0.833913  0.000000   
311  0.705882     1.0  0.288660  0.517182  0.000000   0.0  0.000000  0.000000   
312  0.352941     1.0  0.585567  0.371134  0.157468   0.0  0.398709  0.000000   
313  0.729412     1.0  0.321649  0.632302  0.000000   0.0  0.303128  1.000000   
314  0.823529     1.0  0.222680  0.328179  0.000000   0.0  0.091857  0.000000   
315  0.694118     0.0  0.251546  0.391753  0.192405   0.0  0.411122  0.000000   
316  0.882353     1.0  0.187629  0.381443  0.045063   0.0  0.359980  0.000000   
317  0.552941     1.0  0.274227  0.398625  0.263797   0.0  0.471202  0.000000   
318  0.517647     0.0  0.177320  0.161512  0.351392   0.0  0.426018  0.000000   
319  0.505882     1.0  0.187629  0.429553  0.100759   0.0  0.566783  0.051095   
320  0.764706     1.0  0.171134  0.309278  0.125570   0.0  0.338878  0.000000   
321  0.905882     0.0  0.228866  0.297251  0.125570   0.0  0.338878  0.000000   
322  0.341176     0.0  0.218557  0.458763  0.082532   0.0  0.214002  0.000000   
323  0.317647     1.0  0.263918  0.381443  0.969620   0.0  0.274081  0.000000   
324  0.517647     1.0  0.070103  0.139175  0.000000   0.0  0.000000  0.000000   
325  0.847059     1.0  0.179381  0.152921  0.000000   0.0  0.115690  0.000000   
326  0.858824     1.0  0.261856  0.601375  0.061772   0.0  0.267130  0.000000   
327  0.741176     1.0  0.235052  0.539519  0.013671   0.0  0.048163  0.000000   
328  0.717647     1.0  0.268041  0.455326  0.000000   0.0  0.030536  0.000000   
329  0.811765     1.0  0.542268  0.233677  0.126582   0.0  0.648461  0.000000   
330  0.894118     0.0  0.150515  0.245704  0.425316   0.0  0.303128  0.000000   
331  0.505882     0.0  0.202062  0.685567  0.000000   0.0  0.111221  0.000000   
332  0.811765     1.0  0.156701  0.3539

In [6]:
X_CMD = df_norm_data_cmd.loc[:, features_indexes].values

X_CMD

array([[0.58823529, 1.        , 0.23505155, ..., 0.99158366, 0.22354822,
        0.25546018],
       [0.55294118, 0.        , 0.13608247, ..., 0.32325737, 0.22499906,
        0.23898328],
       [0.83529412, 1.        , 0.25360825, ..., 0.32379821, 0.22500259,
        0.23902274],
       ...,
       [0.54117647, 0.        , 0.29896907, ..., 0.25366253, 0.22498621,
        0.24017501],
       [0.51764706, 1.        , 0.4742268 , ..., 0.34222081, 0.22473814,
        0.23999178],
       [0.51764706, 0.        , 0.25154639, ..., 0.32332324, 0.22499458,
        0.23901556]])

In [7]:
distances_cmd = np.array([[-1,-1,-1]])

for i in range(116):
    for j in range(i+1,116):
            #print(str(i)+' '+str(j))
            sum_sq = np.sum(np.square(X_CMD[i] - X_CMD[j]))
            distance = np.sqrt(sum_sq)
            distances_cmd = np.append(distances_cmd, [[i,j,distance]], axis=0)

distances_cmd


array([[ -1.        ,  -1.        ,  -1.        ],
       [  0.        ,   1.        ,   1.28121074],
       [  0.        ,   2.        ,   0.75389489],
       ...,
       [113.        , 114.        ,   1.20240199],
       [113.        , 115.        ,   0.3403911 ],
       [114.        , 115.        ,   1.22581583]])

In [8]:
distances_cmd = distances_cmd[distances_cmd[:,2].argsort()]

distances_cmd

array([[-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 5.20000000e+01,  1.12000000e+02,  8.40987827e-02],
       [ 2.70000000e+01,  7.00000000e+01,  1.13495378e-01],
       ...,
       [ 2.90000000e+01,  3.90000000e+01,  2.63001883e+00],
       [ 5.80000000e+01,  7.80000000e+01,  2.75231438e+00],
       [ 2.90000000e+01,  5.80000000e+01,  2.76755944e+00]])

# Parei aqui - Calcular as novas amostras artificiais para chegar em 200 instancias

In [9]:
X_CMD_AUGM = X_CMD.copy()

X_CMD_AUGM

array([[0.58823529, 1.        , 0.23505155, ..., 0.99158366, 0.22354822,
        0.25546018],
       [0.55294118, 0.        , 0.13608247, ..., 0.32325737, 0.22499906,
        0.23898328],
       [0.83529412, 1.        , 0.25360825, ..., 0.32379821, 0.22500259,
        0.23902274],
       ...,
       [0.54117647, 0.        , 0.29896907, ..., 0.25366253, 0.22498621,
        0.24017501],
       [0.51764706, 1.        , 0.4742268 , ..., 0.34222081, 0.22473814,
        0.23999178],
       [0.51764706, 0.        , 0.25154639, ..., 0.32332324, 0.22499458,
        0.23901556]])

In [10]:
const_lambda = 0.5

for i in range(1,85):
    #print(str(i))
    #print(distances_cmd[i])
    #print(int(distances_cmd[i][0]))
    #print(int(distances_cmd[i][1]))
    nova_amostra = ((X_CMD[int(distances_cmd[i][0])] - X_CMD[int(distances_cmd[i][1])]) * const_lambda) + X_CMD[int(distances_cmd[i][1])]
    #print(nova_amostra)
    X_CMD_AUGM = np.append(X_CMD_AUGM, [nova_amostra], axis=0)

In [11]:
X_CMD_AUGM

array([[0.58823529, 1.        , 0.23505155, ..., 0.99158366, 0.22354822,
        0.25546018],
       [0.55294118, 0.        , 0.13608247, ..., 0.32325737, 0.22499906,
        0.23898328],
       [0.83529412, 1.        , 0.25360825, ..., 0.32379821, 0.22500259,
        0.23902274],
       ...,
       [0.72352941, 1.        , 0.16185567, ..., 0.3232591 , 0.22493026,
        0.23902345],
       [0.9       , 1.        , 0.17216495, ..., 0.41975   , 0.22658249,
        0.23905295],
       [0.57647059, 1.        , 0.15773196, ..., 0.32319942, 0.22714184,
        0.2392531 ]])

In [12]:
df_norm_augm_data_cmd = pd.DataFrame(X_CMD_AUGM, columns = features_indexes)
df_norm_augm_data_cmd.head(500)

idade  genero    volume     massa      edl1  edl2      edl3      edl4  \
0    0.588235     1.0  0.235052  0.146048  0.103797   0.0  0.191410  0.000000   
1    0.552941     0.0  0.136082  0.159794  0.097215   0.0  0.422542  0.000000   
2    0.835294     1.0  0.253608  0.223368  0.086582   0.0  0.361470  0.000000   
3    0.964706     1.0  0.216495  0.357388  0.000000   0.0  0.282274  0.000000   
4    0.517647     1.0  0.426804  0.379725  0.000000   0.0  0.433217  0.000000   
5    0.835294     1.0  0.315464  0.785223  0.137722   0.0  0.379841  0.000000   
6    0.435294     1.0  0.552577  0.773196  0.259241   0.0  0.332423  0.000000   
7    0.682353     0.0  0.222680  0.164948  0.071392   0.0  0.206306  0.000000   
8    0.364706     1.0  0.113402  0.171821  0.154430   0.0  0.450348  0.181569   
9    0.658824     1.0  0.290722  0.580756  0.014684   0.0  0.615194  0.000000   
10   0.741176     1.0  0.278351  0.271478  0.737215   0.0  0.658391  0.000000   
11   0.847059     1.0  0.513402  0.316151  0.000000   0.0  0.559086  0.000000   
12   1.000000     1.0  0.111340  0.130584  0.000000   0.0  0.536743  0.036496   
13   0.764706     1.0  0.284536  0.396907  0.013671   0.0  0.102284  0.000000   
14   0.611765     1.0  0.138144  0.073883  0.009114   0.0  0.018371  0.000000   
15   0.517647     0.0  0.059794  0.109966  0.000000   0.0  0.133813  0.000000   
16   0.670588     1.0  0.447423  0.847079  0.089620   0.0  0.456058  0.000000   
17   0.847059     1.0  0.177320  0.237113  0.000000   0.0  0.000000  0.000000   
18   0.776471     1.0  0.131959  0.199313  0.000000   0.0  0.000000  0.000000   
19   0.517647     1.0  0.241237  0.372852  0.637975   0.0  0.693893  0.000000   
20   0.352941     1.0  0.362887  0.046392  0.080000   0.0  0.235353  0.000000   
21   0.600000     1.0  0.468041  0.613402  0.108861   0.0  0.665839  0.000000   
22   0.447059     1.0  0.606186  1.000000  0.149873   0.0  0.502731  0.000000   
23   0.729412     1.0  0.123711  0.206186  0.000000   0.0  0.188183  0.000000   
24   0.882353     1.0  0.226804  0.178694  0.000000   0.0  0.188183  0.000000   
25   0.517647     1.0  0.169072  0.240550  0.564051   0.0  0.415839  0.000000   
26   0.647059     0.0  0.175258  0.462199  0.136709   0.0  0.833913  0.000000   
27   0.705882     1.0  0.288660  0.517182  0.000000   0.0  0.000000  0.000000   
28   0.352941     1.0  0.585567  0.371134  0.157468   0.0  0.398709  0.000000   
29   0.729412     1.0  0.321649  0.632302  0.000000   0.0  0.303128  1.000000   
30   0.823529     1.0  0.222680  0.328179  0.000000   0.0  0.091857  0.000000   
31   0.694118     0.0  0.251546  0.391753  0.192405   0.0  0.411122  0.000000   
32   0.882353     1.0  0.187629  0.381443  0.045063   0.0  0.359980  0.000000   
33   0.552941     1.0  0.274227  0.398625  0.263797   0.0  0.471202  0.000000   
34   0.517647     0.0  0.177320  0.161512  0.351392   0.0  0.426018  0.000000   
35   0.505882     1.0  0.187629  0.429553  0.100759   0.0  0.566783  0.051095   
36   0.764706     1.0  0.171134  0.309278  0.125570   0.0  0.338878  0.000000   
37   0.905882     0.0  0.228866  0.297251  0.125570   0.0  0.338878  0.000000   
38   0.341176     0.0  0.218557  0.458763  0.082532   0.0  0.214002  0.000000   
39   0.317647     1.0  0.263918  0.381443  0.969620   0.0  0.274081  0.000000   
40   0.517647     1.0  0.070103  0.139175  0.000000   0.0  0.000000  0.000000   
41   0.847059     1.0  0.179381  0.152921  0.000000   0.0  0.115690  0.000000   
42   0.858824     1.0  0.261856  0.601375  0.061772   0.0  0.267130  0.000000   
43   0.741176     1.0  0.235052  0.539519  0.013671   0.0  0.048163  0.000000   
44   0.717647     1.0  0.268041  0.455326  0.000000   0.0  0.030536  0.000000   
45   0.811765     1.0  0.542268  0.233677  0.126582   0.0  0.648461  0.000000   
46   0.894118     0.0  0.150515  0.245704  0.425316   0.0  0.303128  0.000000   
47   0.505882     0.0  0.202062  0.685567  0.000000   0.0  0.111221  0.000000   
48   0.811765     1.0  0.156701  0.3539

In [13]:
df_norm_augm_data_cmd['target'] = 1
df_norm_augm_data_cmd.head(400)

idade  genero    volume     massa      edl1  edl2      edl3      edl4  \
0    0.588235     1.0  0.235052  0.146048  0.103797   0.0  0.191410  0.000000   
1    0.552941     0.0  0.136082  0.159794  0.097215   0.0  0.422542  0.000000   
2    0.835294     1.0  0.253608  0.223368  0.086582   0.0  0.361470  0.000000   
3    0.964706     1.0  0.216495  0.357388  0.000000   0.0  0.282274  0.000000   
4    0.517647     1.0  0.426804  0.379725  0.000000   0.0  0.433217  0.000000   
5    0.835294     1.0  0.315464  0.785223  0.137722   0.0  0.379841  0.000000   
6    0.435294     1.0  0.552577  0.773196  0.259241   0.0  0.332423  0.000000   
7    0.682353     0.0  0.222680  0.164948  0.071392   0.0  0.206306  0.000000   
8    0.364706     1.0  0.113402  0.171821  0.154430   0.0  0.450348  0.181569   
9    0.658824     1.0  0.290722  0.580756  0.014684   0.0  0.615194  0.000000   
10   0.741176     1.0  0.278351  0.271478  0.737215   0.0  0.658391  0.000000   
11   0.847059     1.0  0.513402  0.316151  0.000000   0.0  0.559086  0.000000   
12   1.000000     1.0  0.111340  0.130584  0.000000   0.0  0.536743  0.036496   
13   0.764706     1.0  0.284536  0.396907  0.013671   0.0  0.102284  0.000000   
14   0.611765     1.0  0.138144  0.073883  0.009114   0.0  0.018371  0.000000   
15   0.517647     0.0  0.059794  0.109966  0.000000   0.0  0.133813  0.000000   
16   0.670588     1.0  0.447423  0.847079  0.089620   0.0  0.456058  0.000000   
17   0.847059     1.0  0.177320  0.237113  0.000000   0.0  0.000000  0.000000   
18   0.776471     1.0  0.131959  0.199313  0.000000   0.0  0.000000  0.000000   
19   0.517647     1.0  0.241237  0.372852  0.637975   0.0  0.693893  0.000000   
20   0.352941     1.0  0.362887  0.046392  0.080000   0.0  0.235353  0.000000   
21   0.600000     1.0  0.468041  0.613402  0.108861   0.0  0.665839  0.000000   
22   0.447059     1.0  0.606186  1.000000  0.149873   0.0  0.502731  0.000000   
23   0.729412     1.0  0.123711  0.206186  0.000000   0.0  0.188183  0.000000   
24   0.882353     1.0  0.226804  0.178694  0.000000   0.0  0.188183  0.000000   
25   0.517647     1.0  0.169072  0.240550  0.564051   0.0  0.415839  0.000000   
26   0.647059     0.0  0.175258  0.462199  0.136709   0.0  0.833913  0.000000   
27   0.705882     1.0  0.288660  0.517182  0.000000   0.0  0.000000  0.000000   
28   0.352941     1.0  0.585567  0.371134  0.157468   0.0  0.398709  0.000000   
29   0.729412     1.0  0.321649  0.632302  0.000000   0.0  0.303128  1.000000   
30   0.823529     1.0  0.222680  0.328179  0.000000   0.0  0.091857  0.000000   
31   0.694118     0.0  0.251546  0.391753  0.192405   0.0  0.411122  0.000000   
32   0.882353     1.0  0.187629  0.381443  0.045063   0.0  0.359980  0.000000   
33   0.552941     1.0  0.274227  0.398625  0.263797   0.0  0.471202  0.000000   
34   0.517647     0.0  0.177320  0.161512  0.351392   0.0  0.426018  0.000000   
35   0.505882     1.0  0.187629  0.429553  0.100759   0.0  0.566783  0.051095   
36   0.764706     1.0  0.171134  0.309278  0.125570   0.0  0.338878  0.000000   
37   0.905882     0.0  0.228866  0.297251  0.125570   0.0  0.338878  0.000000   
38   0.341176     0.0  0.218557  0.458763  0.082532   0.0  0.214002  0.000000   
39   0.317647     1.0  0.263918  0.381443  0.969620   0.0  0.274081  0.000000   
40   0.517647     1.0  0.070103  0.139175  0.000000   0.0  0.000000  0.000000   
41   0.847059     1.0  0.179381  0.152921  0.000000   0.0  0.115690  0.000000   
42   0.858824     1.0  0.261856  0.601375  0.061772   0.0  0.267130  0.000000   
43   0.741176     1.0  0.235052  0.539519  0.013671   0.0  0.048163  0.000000   
44   0.717647     1.0  0.268041  0.455326  0.000000   0.0  0.030536  0.000000   
45   0.811765     1.0  0.542268  0.233677  0.126582   0.0  0.648461  0.000000   
46   0.894118     0.0  0.150515  0.245704  0.425316   0.0  0.303128  0.000000   
47   0.505882     0.0  0.202062  0.685567  0.000000   0.0  0.111221  0.000000   
48   0.811765     1.0  0.156701  0.3539

In [14]:
df_norm_augm_data_cmd.to_csv("../Database/df_database_dados_normalizados_aumentados_minmax_cmd.csv", index = False)